---

- name: Setup bridge
  when: openvpn_bridge
  template:
    src: bridge-interface.j2
    dest: "/etc/network/interfaces.d/{{ openvpn_dev }}"
  register: bridge
  tags: [bridge]

- file:
    path: "/etc/network/interfaces.d/{{ openvpn_dev }}"
    state: absent
  when: not openvpn_bridge
  tags: [bridge]

- name: Enable openvpn network interface
  shell: "ifup br-{{ openvpn_dev }}"
  when: openvpn_bridge
